const ItemActionTypes = {
  FETCH_ITEMS_START: "FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FAILURE: "FETCH_ITEMS_FAILURE",
  SEARCH_ITEMS: "SEARCH_ITEMS",
  TOGGLE_ITEMS_GRID: "TOGGLE_ITEMS_GRID",
  SORT_ITEMS: "SORT_ITEMS",
};

export default ItemActionTypes;
